Review of benchmark-template
cyberbotics/competition-template pull request #1
Opened 2022-11-15 13:54 UTC by Jean-Eudes-le-retour

This is the first draft of the benchmark template repository that can be used to create one's own benchmark.
It is compatible with benchmark.webots.cloud to try it online and to see other participants runs and scores.

2022-11-15 14:52 UTC, Jean-Eudes-le-retour commented
Maybe the instructions should be in the wiki instead of the README file?

2022-11-15 16:27 UTC, Jean-Eudes-le-retour commented
When the repository is generated from template, we loose the wiki and the relative links that came with it. I think it should be best to keep the instructions in the readme

2022-11-16 09:12 UTC, omichel requested changes

2022-11-16 09:12 UTC, omichel commented on ORGANIZER.md
> +   1. ![Create a new Personal Access Token](../../../../settings/tokens/new). Give it a name to remember what it is for and set its "Expiration" to the end of the tournament. You can always set it to
```suggestion
   1. ![Create a new Personal Access Token](../../../../settings/tokens/new). Give it a name to remember what it is for and set its "Expiration" to the end of the tournament. You can always set it to "No expiration" or recreate a token when it expires to allow the automated scripts to continue working. Tick the "repo" scope box, scroll down to the "Generate token" button and click it. Copy the generated code to your clipboard.
```

2022-11-16 09:12 UTC, omichel commented on ORGANIZER.md
> +   1. Go to the repo's ![secrets settings](../../settings/secrets/actions/new) to create a new repository secret. Name it "REPO_TOKEN", paste in the Personal Access Token you just created and finally
```suggestion
   1. Go to the repo's ![secrets settings](../../settings/secrets/actions/new) to create a new repository secret. Name it "REPO_TOKEN". In the "Secret" text area, paste the Personal Access Token you just created and finally click the "Add secret" button.
```

2022-11-16 09:12 UTC, omichel commented on ORGANIZER.md
> +   1. Go to the ![Generate new labels action](../../actions/workflows/generate_labels.yml) page under the Actions tab. Click on "Run workflow" to create automatically the needed labels
```suggestion
   1. Go to the ![Generate new labels action](../../actions/workflows/generate_labels.yml) page under the Actions tab. Click on "Run workflow" to create automatically the needed labels. It may take a few seconds to complete the workflow.
```

2022-11-16 09:12 UTC, omichel commented on ORGANIZER.md
> +   - "worlds" for your Webots scenario
```suggestion
   - [worlds](worlds) for your Webots scenario.
```

2022-11-16 09:12 UTC, omichel commented on ORGANIZER.md
> +   - "protos" if you need extra PROTOs
```suggestion
   - [controllers](controllers) for your robot and supervisor controllers.
   - [plugins](plugins) for the HTML robot windows.
   - [protos](protos) if you need extra PROTOs.
```

2022-11-16 09:12 UTC, omichel commented on ORGANIZER.md
> +5. Make sure that inside the world file the supervisor node has the "synchronization" field set to TRUE and the **robot node** has its **"synchronization" field set to FALSE**.
```suggestion
5. Make sure that inside the world file the supervisor node has the "synchronization" field set to TRUE and the **Robot node** has its **"synchronization" field set to FALSE**.
```

2022-11-16 09:12 UTC, omichel commented on ORGANIZER.md
> +   - Note that on webots.cloud, the listing title of the benchmark and its hover description are defined by the Webots world file: more specifically, the WorldInfo node has a "title" and an "info" fi
```suggestion
   - Note that on [webots.cloud](https://webots.cloud), the listing title of the benchmark and its hover description are defined in the Webots world file: more specifically, the **WorldInfo** node has a "title" and an "info" field which are parsed when submitting the world file to [webots.cloud](https://webots.cloud).
```

2022-11-16 09:12 UTC, omichel commented on ORGANIZER.md
> +6. In order for the automated script to recover the competitors' score correctly, the supervisor needs to print the final performance of the robot controller in the format "performance_line:score" to
This is not very clear to me. Should "performance_line" be replaced with one of "percent", "time-duration", "time-speed" or "distance"? A better explanation and maybe an example would be welcome here. Also, it may be good to display the different options in a table.
We could also hyperlink the ![metric](https://github.com/omichel/my-benchmark/blob/main/webots.yml#L6) to make it clearer where this parameter is defined.

2022-11-16 09:12 UTC, omichel commented on ORGANIZER.md
> +7. Update the fields inside ![webots.yml](../../edit/main/webots.yml):
```suggestion
7. Update the parameters inside ![webots.yml](../../edit/main/webots.yml):
```

2022-11-16 09:12 UTC, omichel commented on ORGANIZER.md
> +   - file: put the relative path to your world file
```suggestion
   - file: set the relative path to your world file.
```

2022-11-16 09:12 UTC, omichel commented on ORGANIZER.md
> +   - maximum-duration: the maximum duration of an evaluation in seconds. Set it not large to avoid long evaluations of broken controllers but not too short to have enough time to finish the task
```suggestion
   - maximum-duration: the maximum duration of an evaluation in seconds. Set it not too large to avoid long evaluations of broken controllers but not too short to have enough time to finish the task.
```

2022-11-16 09:12 UTC, omichel commented on ORGANIZER.md
> +   - metric: should be one of "percent", "time-speed", "time-duration" or "distance". It depends on how the performance is evaluated
```suggestion
   - metric: should be one of "percent", "time-speed", "time-duration" or "distance". It depends on how the performance is evaluated.
```

2022-11-16 09:12 UTC, omichel commented on ORGANIZER.md
> +   - dockerCompose: it is a special path used by the integrated IDE and GitHub actions to locate the default controller. Change "edit_me" to the name of your main controller
```suggestion
   - dockerCompose: it is a special path used by the integrated IDE and GitHub actions to locate the default robot controller. Change "edit_me" to the name of your main robot controller.
```

2022-11-16 09:12 UTC, omichel commented on ORGANIZER.md
> +   1. Don't forget to commit your changes to save them
```suggestion
   1. Don't forget to commit your changes to save them.
```

2022-11-16 09:12 UTC, omichel commented on ORGANIZER.md
> +8. When a controller is evaluated, Webots and the controller are run inside [Docker containers](https://www.docker.com/resources/what-container/). There are two Dockerfiles at the root of the reposit
```suggestion
8. When a controller is evaluated, Webots and the controller are run inside ![Docker containers](https://www.docker.com/resources/what-container/). There are two Dockerfiles at the root of the repository, ![Dockerfile](DockerFile) for the Webots container and ![controller_Dockerfile](controller_Dockerfile) for the controller container which contains the setup of the competitor. The default ![Dockerfile](Dockerfile) will launch in one docker a standard version of Webots with the world file defined in the ![webots.yml](webots.yml#L4) file. The default ![controller_Dockerfile](controller_Dockerfile) will launch in another docker, a python robot controller specified in ![webots.yml](webots.yml#L7).
```

2022-11-16 09:12 UTC, omichel commented on ORGANIZER.md
> +   - If you need a special installation environment for your simulation or controller you can configure the Dockerfiles as needed. The default webots.cloud Docker image already has the tools needed t
```suggestion
   - The default webots.cloud Docker image already has the tools needed to compile and run C, C++ and Python controllers. However, if you need a special environment (for example with specific libraries) for your simulation or supervisor controller you can configure the main [Dockerfile](DockerFile) as needed. Similarly, if competitors have special dependencies (like ROS 2, or some specific Python libraries) for their robot controllers, they can configure their [controller_Dockerfile] accordingly.
```

2022-11-16 10:33 UTC, Jean-Eudes-le-retour commented on ORGANIZER.md
> +8. When a controller is evaluated, Webots and the controller are run inside [Docker containers](https://www.docker.com/resources/what-container/). There are two Dockerfiles at the root of the reposit
The \!\[]() syntax is a weird "hack" I use to make links open in a new tab for GitHub links (on Chrome there's even a small "broken image" icon next to the link), but it seems to only work for GitHub links.
Here we reference files and file lines without asking them to modify them so maybe we don't need to open the links in new tabs, so a \[]() form would be more suited?

2022-11-16 10:33 UTC, Jean-Eudes-le-retour commented on ORGANIZER.md
> +6. In order for the automated script to recover the competitors' score correctly, the supervisor needs to print the final performance of the robot controller in the format "performance_line:score" to
"performance_line" should not be changed, the meta script already knows the metric so the supervisor doesn't need to provide it. I'll add some clarifications.
I think the metric table is a good idea, I'll add it in the clarifications

2022-11-16 11:27 UTC, merged